### ISSUE TITLE
Screen navigation configuration

### ISSUE THREAD

**Issue by AlbertoG22** [BrightCoders-Institute/proyecto-final-bcmay23-rn-t3-teama#2]
## DESCRIPTION

> The objective of this issue is to configure the Stack Navigator in the project to be able to navigate between screens.

```[tasklist]
### Tasks
- [x] Install React Navigation.
- [x] Install required dependencies.
- [x] Make the necessary configurations.
- [x] Create new screens.
- [x] Configure bottom navigation.
```
