### ISSUE TITLE
Login with database

### ISSUE THREAD

**Issue by AlbertoG22** [BrightCoders-Institute/proyecto-final-bcmay23-rn-t3-teama#23]
## REQUIREMENTS / DESCRIPTION
Implement login functionality now with Firebase.

```[tasklist]
### Tasks
- [x] Enable the "Email/Password" sign-in provider on the Firebase Console.
- [x] Implement the funtionality of authentication in the app with React Native logic.
- [x] Create a collection (in Firebase) for the users and with their respective client keys.
- [x] Allow login if the client key is in the database.
- [x] Handling errors of the authentication (provide feedback to the user).
- [x] Redirect to Home Page when login successfully.
```
