### ISSUE TITLE
MyMealsDetails screen

### ISSUE THREAD

**Issue by landillo** [BrightCoders-Institute/proyecto-final-bcmay23-rn-t3-teama#25]
```[tasklist]
### Tasks
- [ ] Create the base for the screen
- [ ] Add the button "View recipe"
- [ ] Add the button "Mark as completed"

```
![Captura de pantalla 2023-08-07 a la(s) 19 03 15](https://github.com/BrightCoders-Institute/proyecto-final-bcmay23-rn-t3-teama/assets/44180680/49673171-37e2-43a5-a003-a1651325acd0)
